server:
  port: 8083

security:
  oauth2:
    resource:
      token-info-uri: http://localhost/oauth/check_token
    client:
      client-id: resource-server
      client-secret: secret
      authorized-grant-types: password