server:
  port: 8083

security:
  oauth2:
    resource:
      token-info-uri: http://localhost/oauth/check_token
    client:
      client-id: resource-server
      client-secret: secret
      authorized-grant-types: password

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cars
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone = Europe/Warsaw
    generate-ddl: true
    show-sql: true